function [InputWaveformdBm,...
    OutputWaveformdBm, PhaseShift] =...
    AMAM_AMPM_gen(InputWaveform, ...
    OutputWaveform, RefImp)
InputWaveformdBm  = mag2db(abs(InputWaveform)) ...
    + 30 - pow2db(RefImp);
OutputWaveformdBm  = mag2db(abs(OutputWaveform)) ...
    + 30 - pow2db(RefImp);
PhaseShift = mod((angle(OutputWaveform) -  ...
    angle(InputWaveform)), 2*pi)*180/pi;
PhaseShift(PhaseShift > 180) = ...
    PhaseShift(PhaseShift > 180) - 360;