function AMAMplot(referencePower, InPower, ...
    OutputWaveformFitMemless, ...
    OutputWaveformFitMem, ...
    RefImp)
figure;
plot(10*log10(InPower) + 30  - ...
    pow2db(RefImp), ...
    10*log10(referencePower) + 30 ... 
    - pow2db(RefImp), '.')
hold on
plot(10*log10(InPower) + 30 ... 
    - pow2db(RefImp), ...
    10*log10(abs(OutputWaveformFitMemless).^2) + 30  - ...
    pow2db(RefImp), '.')
plot(10*log10(InPower) + 30 ... 
    - pow2db(RefImp), ...
    10*log10(abs(OutputWaveformFitMem).^2) + 30  - ...
    pow2db(RefImp), '.')
grid on
xlabel('Input Power (dBm)')
ylabel('Output Power (dBm)')
title('AM/AM')
legend('reference model', 'LUT', 'memPoly')
