function AMPMplot(PhaseShift, InPower, ...
    inRef, OutputWaveformFitMemless, ...
    OutputWaveformFitMem, ...
    RefImp)
figure;
plot(10*log10(InPower) + 30 - ...
    pow2db(RefImp), PhaseShift, '.')
hold on
PhaseShiftMemless = mod((angle(OutputWaveformFitMemless) -  ...
    angle(inRef)), 2*pi)*180/pi;
PhaseShiftMemless(PhaseShiftMemless > 180) = ...
    PhaseShiftMemless(PhaseShiftMemless > 180) - 360;
plot(10*log10(InPower) + 30 - ...
    pow2db(RefImp), PhaseShiftMemless, '.')
PhaseShiftFitMem = mod((angle(OutputWaveformFitMem) -  ...
    angle(inRef)), 2*pi)*180/pi;
PhaseShiftFitMem(PhaseShiftFitMem > 180) = ...
    PhaseShiftFitMem(PhaseShiftFitMem > 180) - 360;
plot(10*log10(InPower) + 30 - ...
    pow2db(RefImp), PhaseShiftFitMem, '.')
grid on
xlabel('Input Power (dBm)')
ylabel('Phase shift')
title('AM/PM')
legend('reference model', 'LUT', 'memPoly')