function out = demod(in, symbolRef, param) 
%% decimate and filter
    % decimate signal
    [ yFreqDec ] = ...
        decimateSignal( in, ...
        1, 1, param.PAModel.interpFactor);
    % filter
    param.rctFilt3 = comm.RaisedCosineTransmitFilter(...
    'Shape',                  'Square root', ...
    'RolloffFactor',          param.PAModel.beta, ...
    'FilterSpanInSymbols',    param.PAModel.Nsym, ...
    'OutputSamplesPerSymbol', param.PAModel.sps);

    paramTest.hfir = param.rctFilt3.coeffs.Numerator;
    paramTest.Nsym = param.PAModel.Nsym;
    paramTest.sampsPerSym = param.PAModel.sps;
    [yqDistFilt, ~] = rx_rrc_filter(yFreqDec, paramTest);
  %% symbol timing synchronization
%   load('dpdLab/meas/symbolRef.mat');
    [ rx_symbol, offset_time, rx_samples ] = ...
        symbol_recoveryCorr( yqDistFilt, ...
        1, param.PAModel.sps, 1, symbolRef, ...
        0, 0);
    %% shift finder
    [ dOutShiftFinder, xShifted, delay, phase ] = ...
        shiftFinder( rx_symbol, ...
        symbolRef, 0); %delay
    %% phase correction
    out =...
        phase_freq_timing_offset(dOutShiftFinder, 0, ...
        -phase, 0);
end