function [rmsErrorTime, rmsErrorFreq] ...
    = GridSearch(InputWaveform, ...
    OutputWaveform, modType, ...
    param_GridSearch)
if param_GridSearch.On
rmsErrorTime = ...
    PACharGridSearchTime(...
    InputWaveform,...
    OutputWaveform,modType, ...
    param_GridSearch);
rmsErrorFreq = ...
    PACharGridSearchFrequency(...
    InputWaveform,...
    OutputWaveform,modType, ...
    param_GridSearch);
else
    rmsErrorTime = [];
    rmsErrorFreq = [];
end