function [PAInputSignal, PAInputSignalFiltered, params] = ...
    PAInputSignalSel(amplifier, ...
    gain, M, pindBm, DataLen, params,...
    PAModel, fig_en)

if params.PAModel.signalSel == 0 % harmonics
    [PAInputSignal, ...
        PAInputSignalFiltered, ...
        params] = ...
        sine_gen(amplifier, ...
        pindBm, DataLen, params,...
        PAModel, fig_en);
elseif params.PAModel.signalSel == 1 % QAM
    [PAInputSignal, ...
        PAInputSignalFiltered, params] = ...
        QAM_mod(amplifier, ...
        gain, M, pindBm, DataLen,...
        params, PAModel, fig_en);
end
x = PAInputSignal;
save('dpdLab/x.mat', 'x');
paramsDemod = params;
save('dpdLab/paramsDemod.mat', 'paramsDemod');