function [] ...
    = SaveDataToDpd(InputWaveform, ...
    numFrames)

frameSize = floor(length(InputWaveform)/numFrames);
paIn.signals.values = double(reshape(InputWaveform(...
    1:frameSize*numFrames,1),numFrames,frameSize));
paIn.signals.dimensions = frameSize;
paIn.time = [];
% save('PAcoefficientsAndInput.mat','modType',...
% 'fitCoefMatMem','memLen','degLen','paIn',...
% 'results.LinearGain')
