function [OutputWaveformAfterDPDPA, OutputWaveformAfterDPD,...
    inOutTableDPD] ...
    = DPDModelEstLut(param, results, ...
    figEn)
gaindB = 0;
gainCoefAr = sqrt(db2pow(gaindB));
inOutTableDPD = GainVsInPowAndTableGenDPD(...
    gainCoefAr * results.InputWaveform,...
    results.OutputWaveform, ... 
    param.PAModel.RefImp, param.PAModel.PALinearGain, figEn);
%% NaN del
% input power
inOutTableDPD(:, 1) = NaNReplace(inOutTableDPD(:, 1), "InputPower", 0);
% output power
inOutTableDPD(:, 2) = NaNReplace(inOutTableDPD(:, 2), "OutputPower", 0);
% phase
inOutTableDPD(:, 3) = NaNReplace(inOutTableDPD(:, 3), "Phase", 0);
%
dpdModel = comm.MemorylessNonlinearity('Method','Lookup table','Table',...
    inOutTableDPD,'ReferenceImpedance', param.PAModel.RefImp); %

PowdBm  = mag2db(abs(results.InputWaveform)) ...
    + 30 - pow2db(param.PAModel.RefImp);

OutputWaveformAfterDPD = dpdModel(results.InputWaveform);
% pa memoryless model
% [results.OutputWaveformFitMemless, results.pa] ...
%     = PAMemlessModel(results.inOutTableDPD, results.InputWaveform, ...
%     results.OutputWaveform, results.sampleRate,...
%     param.PAModel.RefImp, ...
%     1);
%%
if param.MatPAModel
    OutputWaveformAfterDPDPA = param.amplifier(OutputWaveformAfterDPD);
else
    OutputWaveformAfterDPDPA = [];
end
