function [OutputWaveformAfterDPDPA, OutputWaveformAfterDPD,...
    inOutTableDPD] ...
    = DPDModelEstLut(param, results, ...
    figEn)
gaindB = 0;
gainCoefAr = sqrt(db2pow(gaindB));
inOutTableDPD = GainVsInPowAndTableGenDPD(...
    results.OutputWaveformdBm,...
    gaindB + results.InputWaveformdBm, gainCoefAr * results.InputWaveform,...
    results.OutputWaveform, figEn);

%
dpdModel = comm.MemorylessNonlinearity('Method','Lookup table','Table',...
    inOutTableDPD,'ReferenceImpedance', param.PAModel.RefImp);

OutputWaveformAfterDPD = dpdModel(results.InputWaveform);
% pa memoryless model
% [results.OutputWaveformFitMemless, results.pa] ...
%     = PAMemlessModel(results.inOutTableDPD, results.InputWaveform, ...
%     results.OutputWaveform, results.sampleRate,...
%     param.PAModel.RefImp, ...
%     1);
%%
if param.MatPAModel
    OutputWaveformAfterDPDPA = param.amplifier(OutputWaveformAfterDPD);
else
    OutputWaveformAfterDPDPA = [];
end
