function [inOutTableDPD,...
    OutputWaveformAfterDPDPALut,...
    OutputWaveformAfterDPDLut,...
    inOutTableDPD] =...
    LutPACharDpd(OutputWaveform, InputWaveform,...
    RefImp, sampleRate, figEn)
%% PA model LUT (no memory)
    inOutTable = GainVsInPowAndTableGen(...
        OutputWaveform,...
        InputWaveform, RefImp, figEn);

    %% pa memoryless model
    [results.OutputWaveformFitMemless, results.pa] ...
        = PAMemlessModel(inOutTable, InputWaveform, ...
        OutputWaveform, sampleRate,...
        RefImp, ...
        0);
    %% dpd test lut
    % close all
    [OutputWaveformAfterDPDPALut,...
        OutputWaveformAfterDPDLut,...
        inOutTableDPD] = ...
        DPDModelEstLut(param, results, 1);
    % results.OutputWaveformFitMemless = results.OutputWaveform;
  