% Design and normalize filter.
function [signalOut] =...
    rx_rrc_filterNew(signalIn,...
    hfir, Nsym, ...
    sampsPerSym)

% Filter at the receiver.
yr = upfirdn([(signalIn);],... % zeros(param.Nsym*param.sampsPerSym/2, 1)
    hfir, 1, sampsPerSym); %param.sampsPerSym

signalOut = yr(Nsym/2+1:...
    end-Nsym/2);
