function [evm_rms]=evm_meas(ref,signal)%,ref_power
% evm = 100*(((real(ref)-...
%     real(signal)).^2+(imag(ref)-imag(signal)).^2)...
%     ./abs(ref).^2);
min_len = min([length(ref) length(signal)]);
ref = ref(1:min_len);
signal = signal(1:min_len);
evm = ((real(ref)-...
    real(signal)).^2+(imag(ref)-imag(signal)).^2)...
    ./mean(abs(ref));
evm_rms = 100*sqrt(mean(evm));
